function mri12
rev = '$Rev: 1 $';
SPMid = spm('FnBanner',mfilename,rev);
[dummy,Fgraph,dummy2] = spm('FnUIsetup','MRI12');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','ioi11.man','',Fgraph,'MRI12');
fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
    'Label',	'MRI12',...
    'Separator',	'on',...
    'Tag',		'MRI12',...
    'HandleVisibility','on');

h01 = uimenu(h0,...
	'Label',	'Dicom convert',...
	'Separator',	'off',...
	'Tag',		'Dicom convert',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.mri12.utilities.dicom1'');',...
	'HandleVisibility','on');