%% This script register the tmap generated by SPM into the template generated by ANTs
clear variables; close all; clc
subj = 19:24;   % desired subject for analysis

%% Tmap generation (first level analysis)
path_stat = mri_BOLD_CO2_old_rats(subj);

%% Create the template from the T1 images (see ANTScreateNormTemp.sh script for the parameters)
create_template = 0;
template_dir = '/Volumes/hd2_local/users_local/jfpp/data/Hypercapnia/template_creation_young_64x64x12';
if create_template == 1
    cmd = 'bash ~/ants/ANTScreateNormTemp.sh';
    unix(cmd);
end
pre='NORMHC';
ext='_c3d_bet_n4c_T1';

%% Register the tmaps to the template
template_dir = '/Volumes/hd2_local/users_local/jfpp/data/Hypercapnia/template_creation_young_64x64x12';
param.affine = 1;
param.warp = 1;
for su = subj
    sus = num2str(su+1);
    input.tmap = fullfile(path_stat{su},'SPM.mat');
    input.affine = fullfile(template_dir,[pre sus ext 'Affine.txt']);
    input.warp = fullfile(template_dir,[pre sus ext 'Warp.nii']);
    input.template = fullfile(template_dir,'NORMtemplate.nii.gz');
    output.rtmap = fullfile(path_stat{su},'SPM_to_T1.mat');
    output.nifti_tmap = fullfile(path_stat{su},'spmT.nii');
    output.nifti_rtmap = fullfile(path_stat{su},'spmT_reg_to_T1.nii');
    register_tmap_to_template(input,output,param)
end

%% Apply the second level analysis
spm('Defaults','fMRI');
spm_jobman('initcfg'); % SPM8 only

clear jobs
jobs{1}.util{1}.cdir.directory = cellstr(data_path);
spm_jobman('run',jobs);

f = spm_select('FPList', fullfile(data_path,'cons_can'), '^con_.*\.img$') ;

clear jobs

jobs{1}.util{1}.md.basedir = cellstr(data_path);
jobs{1}.util{1}.md.name = 'canonical';

jobs{2}.stats{1}.factorial_design.dir = cellstr(fullfile(data_path,'canonical'));
jobs{2}.stats{1}.factorial_design.des.t1.scans = cellstr(f);

jobs{2}.stats{2}.fmri_est.spmmat = cellstr(fullfile(data_path,'canonical','SPM.mat'));

jobs{2}.stats{3}.con.spmmat = cellstr(fullfile(data_path,'canonical','SPM.mat'));
jobs{2}.stats{3}.con.consess{1}.fcon.name = 'Faces vs Baseline: Canonical HRF';
jobs{2}.stats{3}.con.consess{1}.fcon.convec{1} = 1;

jobs{2}.stats{4}.results.spmmat = cellstr(fullfile(data_path,'canonical','SPM.mat'));
jobs{2}.stats{4}.results.conspec(1).contrasts = Inf;
jobs{2}.stats{4}.results.conspec(1).threshdesc = 'FWE';

spm_jobman('run',jobs);

