%% DEPENDENCIES
% unring.m : https://bitbucket.org/reisert/unring
%% CONFIGURE
%%-------------------------------------------------------------------------
% FORMAT: {'FOLDER',{'SUBFOLDER',{'keyword','value','param','value/rename'},'SUBFOLDER',{'keyword','value','param','value'}},{'keyword','value','param','value'},...}
copytype = {'qMT',{'SIRFSE',{'keyword','*sirfse*'       ,'param',{'ti'}},...
                     'SPGR',{'keyword','qMT_*'          ,'param',{'mtfrq','flipmt/mtflip','tr','te'}},...
                  },...
      'fieldsmap',    {'B0',{'keyword','b0_mapping*'    ,'param',{'te/te1','te2'}, 'phase', true},...
                       'B1',{'keyword','*b1map_MFA*'    ,'param',{'flip1/flipangle'}}
                      },...
	         'T1',          {'keyword','*t1map*'        ,'param',{'ti'}},...
  'ProtonDensity',          {'keyword','*MTV*'          ,'param',{'flip1/flipangle','tr','te'}},...
             'T2',          {'keyword','*MWF*'          ,'param',{'flip1/flipangle','tr','te','ne/nechos','nt/averages'}},...
      'Diffusion',{'Qspace1D',...
                     {'EPI',{'keyword','epi*d*D*','param',{'te','tr','.scheme'}},...
                      'FSE',{'keyword','fsems*diff*','param',{'te','tr','.scheme'}},...
                     },...
                   'Qspace3D',...
                     {'EPI',{'keyword','epip*NODDI*'    ,'param',{'te','tr','.scheme'}},...
                      'FSE',{'keyword','epip*NODDI*'    ,'param',{'te','tr','.scheme'}},...
                     },...
                  },...
           };

%% CREATE OUTPUT FOLDER AND CD TO THIS DIRECTORY
animal = 'Rat'
mkdir(animal)
cd(animal)
region = 'CC'
mkdir(region)
cd(region)
date   = '20170718'
mkdir(date)
cd(date)

%% ORGANIZE IN CURRENT FOLDER
datafolder = '~/data/ICM/s_20171130_TEST_RESCAN';
organizeqmr(copytype,datafolder)