
%% Organizsation
index = schemeKM(:,9)==3;
dro = [0 0 0 schemeKM(index,1)'.*schemeKM(,4)']/80E-6;
dpe = [0 0 0 schemeKM(index,2)'.*schemeKM(:,4)']/80E-6;
dsl = [0 0 0 schemeKM(:,3)'.*schemeKM(:,4)']/80E-6;

%% add virgule
fid = fopen('AxCaliber_Opt1.txt','w+');
fprintf(fid, '%s\n\n%s\n%s\n\n%s\n\n',...
    'zero_gf',...
    '// Use temporary variables $dro, $dpe, $dsl to avoid',...
    '// errors about unequal array sizes for dro, dpe, dsl',...
    '// Start with a b=0');

dir_str={'dro','dpe','dsl'};
dir = [dro;dpe;dsl];
for i_dir=1:length(dir_str)
    dro_string = ['$' dir_str{i_dir} ' = $' dir_str{i_dir} ', ' num2str(dir(i_dir,1))];
    fprintf(fid, '\n\n%s',['$' dir_str{i_dir} ' = ' num2str(dir(i_dir,1))]);
    for i=2:length(dro)
        if mod(i-1,6)==0
            dro_string = ['$' dir_str{i_dir} ' = $' dir_str{i_dir} ', ' num2str(dir(i_dir,i))];
            fprintf(fid, '\n%s',dro_string);
        else
            dro_string = [', ' num2str(dir(i_dir,i))];
            fprintf(fid, '%s',dro_string);
        end
    end
end
fprintf(fid, '\n%s\n%s\n%s\n\n%s\n\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n',... 
    'dro = $dro',...
    'dpe = $dpe',...
    'dsl = $dsl',...
    'set_gf_array',...
    'create(''nbval'',''real'',''current'',0)',...
    'create(''nbzero'',''real'',''current'',0)',...
    'create(''nbdirs'',''real'',''current'',0)',...
    'create(''dstart'',''real'',''current'',0)',...
    ['nbval=' num2str(length(dro))],...
    ['nbzero= 3'],...
    ['nbdirs='  num2str(length(dro))]);

fclose(fid);

